version: "3.9"
   
services:
  db:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./Postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - groceryapp
  web:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./BackEnd:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    networks:
      - groceryapp
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
      - web
    restart: always
    networks:
      - groceryapp

networks:
  groceryapp: