# Generated by Django 4.0.3 on 2022-04-04 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, null=True, related_name='grocery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.FloatField()),
                ('is_purchased', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, max_length=200, null=True)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.grocerylist')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='grocery.unittype')),
            ],
        ),
    ]
