# Generated by Django 4.0.3 on 2022-04-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_alter_grocerylist_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='shared_with',
        ),
    ]
