# Generated by Django 4.0.3 on 2022-04-07 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0006_remove_grocerylist_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='grocery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
